### PR TITLE
added image to home page, changed styling

### PR DESCRIPTION
**Pull request by eang0521**
A R1

Added image to home page, changed styling

### CODE REVIEW

**Comment by eang0521** [comment]
A R2

Added image to apprenticeship.js

**Comment by eang0521** [comment]
A R3

Updated font styling

**Comment by eang0521** [comment]
A R4

Added horizontal rule and left text-align

**Comment by eang0521** [comment]
A R5

Added "Contact Us" section

**Comment by eang0521** [comment]
image

Added second image to home page

**Comment by eang0521** [comment]
image

Added image to about page

**Review by jontsai — APPROVED** [review]

**Pull request merged**
